export const businessData = [
  { business: "Johnson Bakery", businessEmail: "contact@johnsonbakery.com" },
  { business: "Smith Electronics", businessEmail: "support@smithelectronics.com" },
  { business: "Williams Consulting", businessEmail: "info@williamsconsulting.com" },
  { business: "Brown Fitness", businessEmail: "hello@brownfitness.com" },
  { business: "Davis Design Studio", businessEmail: "team@davisdesign.com" },
  { business: "Miller Motors", businessEmail: "sales@millermotors.com" },
  { business: "Wilson Marketing", businessEmail: "contact@wilsonmarketing.com" },
  { business: "Taylor Travel", businessEmail: "bookings@taylortravel.com" },
  { business: "Anderson Art Gallery", businessEmail: "info@andersonart.com" },
  { business: "Thomas Tech", businessEmail: "support@thomastech.com" },
  { business: "Martin Media", businessEmail: "contact@martinmedia.com" },
  { business: "Jackson Jewelry", businessEmail: "orders@jacksonjewelry.com" },
  { business: "White Wellness", businessEmail: "hello@whitewellness.com" },
  { business: "Harris Hardware", businessEmail: "sales@harrishardware.com" },
  { business: "Clark Clothing", businessEmail: "shop@clarkclothing.com" },
  { business: "Lewis Logistics", businessEmail: "info@lewislogistics.com" },
  { business: "Walker Wines", businessEmail: "support@walkerwines.com" },
  { business: "Hall Home Decor", businessEmail: "contact@hallhomedecor.com" },
  { business: "Young Yoga", businessEmail: "hello@youngyoga.com" },
  { business: "King Kitchens", businessEmail: "orders@kingkitchens.com" },
];
