export const friendsData = [
  { username: "Alice Johnson", email: "alice.johnson@example.com" },
  { username: "Bob Smith", email: "bob.smith@example.com" },
  { username: "Carol Williams", email: "carol.williams@example.com" },
  { username: "David Brown", email: "david.brown@example.com" },
  { username: "Eva Davis", email: "eva.davis@example.com" },
  { username: "Frank Miller", email: "frank.miller@example.com" },
  { username: "Grace Wilson", email: "grace.wilson@example.com" },
  { username: "Henry Taylor", email: "henry.taylor@example.com" },
  { username: "Ivy Anderson", email: "ivy.anderson@example.com" },
  { username: "Jack Thomas", email: "jack.thomas@example.com" },
  { username: "Karen Martin", email: "karen.martin@example.com" },
  { username: "Leo Jackson", email: "leo.jackson@example.com" },
  { username: "Mia White", email: "mia.white@example.com" },
  { username: "Noah Harris", email: "noah.harris@example.com" },
  { username: "Olivia Clark", email: "olivia.clark@example.com" },
  { username: "Paul Lewis", email: "paul.lewis@example.com" },
  { username: "Quinn Walker", email: "quinn.walker@example.com" },
  { username: "Ruby Hall", email: "ruby.hall@example.com" },
  { username: "Sam Young", email: "sam.young@example.com" },
  { username: "Tina King", email: "tina.king@example.com" },
];
